### ISSUE TITLE
There's something wrong with AAAI 2019 links

### ISSUE THREAD

**Issue by ffffatgoose** [jokieleung/awesome-visual-question-answering#4]
I click the paper "Differential Networks for Visual Question Answering", and the page is not right……
![image](https://user-images.githubusercontent.com/44337029/76947509-af69ee80-6940-11ea-95cb-9030b0179035.png)
And so as the third one "Dynamic Capsule Attention for Visual Question Answering" :)

**Comment by jokieleung** [comment]
should be the AAAI lib problem, pls google the paper for PDF
